apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      release: stabel
  template:
    metadata:
      labels:
        app: myapp
        release: stabel
        env: test
    spec:
      containers:
      - name: myapp
        image: openresty/openresty-lua:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: myapp
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  tls:
    - hosts:
      - ahyw724.com
      - ahyw724.com.cn
      secretName: tls-secret
  rules:
    - host: ahyw724.com
      http:
        paths:
        - path: /
          backend:
            serviceName: myapp
            servicePort: 80
    - host: ahyw724.com.cn
      http:
        paths:
        - path: /lua/api
          backend:
            serviceName: myapp
            servicePort: 80